stages:
  - name: Build and Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./docker/Dockerfile
          buildContext: .
          tag: utm-tools/utmsim
          pushRemote: true
          registry: mosaix-swim.dev.dkr.frequentis.frq
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
  - name: Create or update workload
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
timeout: 60
notification: {}
